export { About } from 'pages/about/About'
export { Fetch } from 'pages/fetch/Fetch'
export { Home } from 'pages/home/Home'
export { NotFound } from 'pages/not-found/NotFound'
export { JobList } from 'pages/job-feed/JobList'
export { Job } from 'pages/layout-page/Job'
